/iiwa:
    joint_state_controller:
      type: "joint_state_controller/JointStateController"
      publish_rate: 50
  
    iiwa_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint_a1
        - joint_a2
        - joint_a3
        - joint_a4
        - joint_a5
        - joint_a6
        - joint_a7
      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: &stop_vel_tol 0.05
        joint_a1: {trajectory: &traj_tol 0.01, goal: &goal_tol 0.01}
        joint_a2: {trajectory: *traj_tol, goal: *goal_tol}
        joint_a3: {trajectory: *traj_tol, goal: *goal_tol}
        joint_a4: {trajectory: *traj_tol, goal: *goal_tol}
        joint_a5: {trajectory: *traj_tol, goal: *goal_tol}
        joint_a6: {trajectory: *traj_tol, goal: *goal_tol}
        joint_a7: {trajectory: *traj_tol, goal: *goal_tol}
      stop_trajectory_duration: &stop_traj_dur 0.5
      gains:
        joint_a1: {p: 10.0, i: 1, d: 1.0}
        joint_a2: {p: 10.0, i: 1, d: 1.0}
        joint_a3: {p: 10.0, i: 1, d: 1.0}
        joint_a4: {p: 10.0, i: 1, d: 1.0}
        joint_a5: {p: 10.0, i: 1, d: 1.0}
        joint_a6: {p: 10.0, i: 1, d: 1.0}
        joint_a7: {p: 10.0, i: 1, d: 1.0}
    
    support_and_iiwa_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - world_to_supportX
        - supportX_to_supportY
        - supportY_to_agv
        - joint_a1
        - joint_a2
        - joint_a3
        - joint_a4
        - joint_a5
        - joint_a6
        - joint_a7
      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: *stop_vel_tol
        joint_a1: {trajectory: *traj_tol, goal: *goal_tol}
        joint_a2: {trajectory: *traj_tol, goal: *goal_tol}
        joint_a3: {trajectory: *traj_tol, goal: *goal_tol}
        joint_a4: {trajectory: *traj_tol, goal: *goal_tol}
        joint_a5: {trajectory: *traj_tol, goal: *goal_tol}
        joint_a6: {trajectory: *traj_tol, goal: *goal_tol}
        joint_a7: {trajectory: *traj_tol, goal: *goal_tol}
      stop_trajectory_duration: *stop_traj_dur
      gains:
        world_to_supportX: {p: 10.0, i: 1, d: 1.0}
        supportX_to_supportY: {p: 10.0, i: 1, d: 1.0}
        supportY_to_agv: {p: 10.0, i: 1, d: 1.0}
        joint_a1: {p: 10.0, i: 1, d: 1.0}
        joint_a2: {p: 10.0, i: 1, d: 1.0}
        joint_a3: {p: 10.0, i: 1, d: 1.0}
        joint_a4: {p: 10.0, i: 1, d: 1.0}
        joint_a5: {p: 10.0, i: 1, d: 1.0}
        joint_a6: {p: 10.0, i: 1, d: 1.0}
        joint_a7: {p: 10.0, i: 1, d: 1.0}
  